import Head from "next/head";
import { FileInput, pdfUpload, cerUpload } from "country-identity-kit";
import { useState } from "react";

export default function Home() {
  const [signedPdfData, setSignedPdfData] = useState(Buffer.from([]));
  const [signature, setSignature] = useState("");
  const [msgBigInt, setMsgBigInt] = useState<bigint>();
  const [sigBigInt, setSigBigInt] = useState<bigint>();
  const [modulusBigInt, setModulusBigInt] = useState<bigint>();

  const handlePdfChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const { signature, signedData } = await pdfUpload(e);
    setSignature(signature);
    setSignedPdfData(signedData);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h1>Welcome to Country Identity Example</h1>
        <p>Prove your anon addhaar ownership</p>

        <FileInput onChange={handlePdfChange} />

        <FileInput
          onChange={async (e) => {
            const { msgBigInt, sigBigInt, modulusBigInt } = await cerUpload(
              e,
              signedPdfData,
              signature
            );

            setMsgBigInt(msgBigInt);
            setSigBigInt(sigBigInt);
            setModulusBigInt(modulusBigInt);
          }}
        />
      </main>
    </>
  );
}
